questions =  [
    {"id": 0, "question": "Freedom of business is the best practical way a society can prosper.", "effects": {"right": 1}},
    {"id": 1, "question": "Charity is a better way of helping those in need than social welfare.", "effects": {"right": 1}},
    {"id": 2, "question": "Wages are always fair, as employers know best what a worker's labour is worth.", "effects": {"right": 1}},
    {"id": 3, "question": "It is \"human nature\" to be greedy.", "effects": {"right": 1}},
    {"id": 4, "question": "\"Exploitation\" is an outdated term, as the struggles of 1800s capitalism don't exist anymore.", "effects": {"right": 1}},
    {"id": 5, "question": "Organisations and corporations cannot be trusted and need to be regulated by the government.", "effects": {"right": -1}},
    {"id": 6, "question": "A government that provides for everyone is an inherently good idea.", "effects": {"right": -1}},
    {"id": 7, "question": "The current welfare system should be expanded to further combat inequality.", "effects": {"right": -1}},
    {"id": 8, "question": "Land should not be a commodity to be bought and sold.", "effects": {"right": -1}},
    {"id": 9, "question": "All industry and the bank should be nationalised.", "effects": {"right": -1}},
    {"id": 10, "question": "Sometimes it is right that the government may spy on its citizens to combat extremists and terrorists.", "effects": {"auth": 1}},
    {"id": 11, "question": "Authority figures, if morally correct, are a good thing for society.", "effects": {"auth": 1}},
    {"id": 12, "question": "Strength is necessary for any government to succeed.", "effects": {"auth": 1}},
    {"id": 13, "question": "Only the government can fairly and effectively regulate organisations.", "effects": {"auth": 1}},
    {"id": 14, "question": "Society requires structure and bureaucracy in order to function.", "effects": {"auth": 1}},
    {"id": 15, "question": "The government should be less involved in the day to day life of its citizens.", "effects": {"auth": -1}},
    {"id": 16, "question": "Without democracy, a society is nothing.", "effects": {"auth": -1}},
    {"id": 17, "question": "Jury nullification should be legal.", "effects": {"auth": -1}},
    {"id": 18, "question": "The smaller the government, the freer the people.", "effects": {"auth": -1}},
    {"id": 19, "question": "The government should, at most, provide emergency services and law enforcement.", "effects": {"auth": -1}},
    {"id": 20, "question": "Two consenting individuals should be able to do whatever they want with each other, even if it makes me uncomfortable.", "effects": {"prog": 1}},
    {"id": 21, "question": "An individual's body is their own property, and they should be able to do anything they desire to it.", "effects": {"prog": 1}},
    {"id": 22, "question": "A person should be able to worship whomever or whatever they want.", "effects": {"prog": 1}},
    {"id": 23, "question": "Nudism is perfectly natural.", "effects": {"prog": 1}},
    {"id": 24, "question": "Animals deserve certain universal rights.", "effects": {"prog": 1}},
    {"id": 25, "question": "Homosexuality is against my values.", "effects": {"prog": -1}},
    {"id": 26, "question": "Transgender individuals should not be able to adopt children.", "effects": {"prog": -1}},
    {"id": 27, "question": "Drugs are harmful and should be banned.", "effects": {"prog": -1}},
    {"id": 28, "question": "The death penalty should exist for certain crimes.", "effects": {"prog": -1}},
    {"id": 29, "question": "Victimless crimes should still be punished.", "effects": {"prog": -1}}
];
